# 启动基础应用
version: '3.5'
services:
#  传递性
  springcloud-eurakeserver-master:
    image: springcloud/eurakeserver:0.0.1-SNAPSHOT
    networks:
      network:
        ipv4_address: 172.16.0.2
#   重写entrypoint和cmd
    entrypoint:
      - java
      - -jar
      - --spring.profiles.active=master
      - /app/discovery-server.jar

  springcloud-eurakeserver-slave:
    image: springcloud/eurakeserver:0.0.1-SNAPSHOT
    networks:
      network:
        ipv4_address: 172.16.0.3
#   重写entrypoint和cmd
    entrypoint:
      - java
      - -jar
      - --spring.profiles.active=slave
      - /app/discovery-server.jar



networks:
  network:
    name: springcloud_net
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.0.0/16
#networks:
#  default:
#    external:
#      name: springcloud_net
