######### 从配置中心读取,如果读取成功则替换,否则采用下面默认配置 ###########
info:
  component: Application Server ${spring.application.name}
# 加入服务发现
#server:
#  port: 8012 # 与从config中心拿到的端口信息不同
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
#   客户端请求时间
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
#   配合上面 'prefer-ip-address' ,具体参数查看 HostInfoEnvironmentPostProcessor
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
# 应用管理
management:
  health:
    refresh:
      enabled: true
  security:
    enabled: false
#loadbalance 算法
#1  BestAvailableRule：最小并发
#2  ZoneAvoidanceRule：性能和可用性最优
#3  AvailabilityFilteringRule：默认算法 去除熔断失败和高并发，使用 RoundRobinRule 轮询选择
#4  RoundRobinRule：轮询
#5  WeightedResponseTimeRule：响应时间最小
#6  !ResponseTimeWeightedRule：废弃，使用WeightedResponseTimeRule
#7  RandomRule：随机选择
#8  RetryRule：默认500毫秒，不断使用 RoundRobinRul 轮询选择
spring-cloud-application-a: #本应用名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule #默认
# ribbon 设置是否立马加载
ribbon:
  eager-load:
    enabled: true
    clients: ${spring.application.name}
#  feign 配置文件
feign:
  compression:
    request:
      mime-types:
      - "text/xml"
      - "application/xml"
      - "application/json"
      min-request-size: 2048
#hystrix 配置
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 2000
  dashboard:
    enable-ignore-connection-close-header: false
############### 日志  ###############
debug: false # true时输出更多
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.boot: info
    com.fansin.spring.cloud: debug
#sleuth-zipkin
spring:
  sleuth:
    enabled: true
#   这里默认采集比较低,需要多次刷新才能在zipkin看到,设置太大会耗性能
    sampler:
      percentage: 0.1
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: http://127.0.0.1:9411/
    enabled: true
    compression:
      enabled: true
  profiles:
    active: a
#springboot admin
  boot:
    admin:
      url: http://127.0.0.1:8080
#sleuth-zipkin
---
spring:
  profiles: a
  application:
    name: spring-cloud-application-a
server:
  port: 8011
# 用户配置信息 配置调用服务接口
ServiceId:
  RibbonController: spring-cloud-application-b
  FeignController: ${ServiceId.RibbonController}
---
spring:
  profiles: b
  application:
    name: spring-cloud-application-b
server:
  port: 8012
# 用户配置信息 配置调用服务接口
ServiceId:
  RibbonController: spring-cloud-application-a
  FeignController: ${ServiceId.RibbonController}
