# 配置config中心
spring:
  application:
    name: spring-cloud-application-a
  cloud:
    config:
      uri: http://127.0.0.1:8888,http://127.0.0.1:8889

######### 从配置中心读取,如果读取成功则替换,否则采用下面默认配置 ###########
info:
  component: Application Server ${spring.application.name}
# 加入服务发现
server:
  port: 8011 # 与从config中心拿到的端口信息不同
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true
# 应用管理
management:
  health:
    refresh:
      enabled: true
  security:
    enabled: false
#loadbalance 算法
#1  BestAvailableRule：最小并发
#2  ZoneAvoidanceRule：性能和可用性最优
#3  AvailabilityFilteringRule：去除熔断失败和高并发，使用 RoundRobinRule 轮询选择
#4  RoundRobinRule：轮询
#5  WeightedResponseTimeRule：响应时间最小
#6  !ResponseTimeWeightedRule：废弃，使用WeightedResponseTimeRule
#7  RandomRule：随机选择
#8  RetryRule：默认500毫秒，不断使用 RoundRobinRul 轮询选择
spring-cloud-application-a: #本应用名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule #默认

# 用户配置信息 配置调用服务接口
invokeService: spring-cloud-application-a