server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 0
