#应用配置
############# master ################
spring:
  profiles:
    active: master
############# slave ################
#spring:
#  profiles:
#    active: slave
#acturator info
info:
  component: Discovery Server ${spring.profiles.active}
#多台服务统一配置,然后启动不同的profile即可,目前为2台
--- #分割配置
spring:
  profiles: master
server:
  port: 8761
peer:
  server:
    port: 8762 #slave的端口
    hostname: 127.0.0.1 #slave 主机
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
#   期待下次心跳
    lease-expiration-duration-in-seconds: 60
#   超时移除客户端
    lease-renewal-interval-in-seconds: 30

  client:
    serviceUrl:
      defaultZone: http://${peer.server.hostname}:${peer.server.port}/eureka/ # 带目录
  server:
#   网络中断后自我保护
    enable-self-preservation: true
#   清理无效节点
    eviction-interval-timer-in-ms: 60
#多台服务统一配置,然后启动不同的profile即可,目前为2台
---
spring:
  profiles: slave
server:
  port: 8762
peer:
  server:
    port: 8761 #master端口
    hostname: 127.0.0.1 #master主机
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${peer.server.hostname}:${peer.server.port}/eureka/
