server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/