# 启动基础应用
version: '3.5'
services:
  springcloud-mariadb-publisher:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      network:
        ipv4_address: 172.16.0.4
    volumes:
      - /home/fansin/IdeaProjects/spring-cloud/jta-atomikos/src/main/resources/sql/publisher.sql:/docker-entrypoint-initdb.d/publisher.sql

  springcloud-mariadb-consumer:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      network:
        ipv4_address: 172.16.0.5
    volumes:
          - /home/fansin/IdeaProjects/spring-cloud/jta-atomikos/src/main/resources/sql/consumer.sql:/docker-entrypoint-initdb.d/consumer.sql

volumes:
  consumer:
  publisher:

networks:
  network:
    name: springcloud_net
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.0.0/16
#networks:
#  default:
#    external:
#      name: springcloud_net
